metadata:
  labels:
    expose: true
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: ${project.artifactId}
        hystrix.enabled: true
        hystrix.cluster: default
        version: ${project.version}
    spec:
      volumes:
        # use configmap application.properties to override the app application.yml
        - name: config-volume
          configMap:
            name: ${project.artifactId}
            items:
            - key: application.properties
              path: application.properties
      containers:
        -
          resources:
            requests:
              cpu: "0.2"
              memory: 256Mi
            limits:
              cpu: "1.0"
              memory: 256Mi
          # environment variables take precedence over properties of application.yml and configmap. You can comment them and check the difference with the /properties endpoint result
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}
                  key: message
          volumeMounts:
            - name: config-volume
              mountPath: /deployments/config
            - name: secrets-volume # name must match the volume name
              mountPath: /deployments/secrets
              readOnly: true
